version: '3.3'
services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes: 
      - ./redis-data:/data